apiVersion: v1
kind: ServiceAccount
metadata:
  name: netpol-ctrl
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netpol-ctrl-role
rules:
- apiGroups: [""]
  resources: ["pods","services"]
  verbs: ["get","watch","update","patch","list"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets"]
  verbs: ["get","watch","update","patch","list"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get","watch","update","patch","list"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get","watch","update","patch","list"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: netpol-ctrl-binding
subjects:
- kind: ServiceAccount
  name: netpol-ctrl
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: netpol-ctrl-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netpol-ctrl
  namespace: kube-system
  labels:
    app: netpol-ctrl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netpol-ctrl
  template:
    metadata:
      labels:
        app: netpol-ctrl
    spec:
      serviceAccountName: netpol-ctrl
      containers:
      - name: netpol-ctrl
        image: adykaaa/k8s-netpol-ctrl:0.1.0